# Generated by Django 4.2.1 on 2023-08-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "db_table": "patient_profile",
            },
        ),
    ]
