# Generated by Django 4.2.1 on 2023-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeslot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dateslot",
            name="times",
            field=models.ManyToManyField(
                blank=True, related_name="date_times", to="timeslot.timeslot"
            ),
        ),
    ]
