# Generated by Django 3.2 on 2023-05-17 05:42

import appointment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_price', models.DecimalField(decimal_places=2, default=appointment.models.Appointment.get_default_price, max_digits=5, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('location', models.ForeignKey(default=appointment.models.Appointment.get_default_location, on_delete=django.db.models.deletion.SET_DEFAULT, to='geo.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
