# Generated by Django 4.2.1 on 2023-07-31 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
        ("appointment", "0001_initial"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctorprofile"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.location",
            ),
        ),
    ]
