# Generated by Django 4.2.1 on 2023-07-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geo", "0001_initial"),
        ("speciality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField()),
                (
                    "clinic_phone",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="geo.location"
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(to="speciality.medicalspecialty"),
                ),
            ],
            options={
                "db_table": "clinic",
            },
        ),
    ]
