# Generated by Django 4.2.1 on 2023-08-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField()),
                (
                    "clinic_phone",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("from_day", models.CharField(blank=True, max_length=10, null=True)),
                ("to_day", models.CharField(blank=True, max_length=10, null=True)),
                ("from_hour", models.TimeField(blank=True, null=True)),
                ("to_hour", models.TimeField(blank=True, null=True)),
                (
                    "examination_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="geo.location"
                    ),
                ),
            ],
            options={
                "db_table": "clinic",
            },
        ),
    ]
