# Generated by Django 4.2.1 on 2023-07-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "speciality",
                    models.CharField(max_length=100, verbose_name="speciality"),
                ),
                ("proof_file", models.FileField(upload_to="doctors/certificates/")),
            ],
            options={
                "db_table": "medical_specialty",
            },
        ),
    ]
