# Generated by Django 3.2 on 2023-05-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('specialty', models.CharField(choices=[('allergy_immunology', 'Allergy and Immunology'), ('anesthesiology', 'Anesthesiology'), ('dermatology', 'Dermatology'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('gastroenterology', 'Gastroenterology'), ('general_surgery', 'General Surgery'), ('internal_medicine', 'Internal Medicine'), ('neurology', 'Neurology'), ('obstetrics_gynecology', 'Obstetrics and Gynecology'), ('ophthalmology', 'Ophthalmology'), ('orthopedic_surgery', 'Orthopedic Surgery'), ('otolaryngology', 'Otolaryngology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('urology', 'Urology')], max_length=50, verbose_name='Specialty')),
            ],
        ),
    ]
