# Generated by Django 3.2 on 2023-05-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalspecialty',
            name='specialty',
            field=models.CharField(choices=[('allergy_immunology', 'Allergy and Immunology'), ('anesthesiology', 'Anesthesiology'), ('dermatology', 'Dermatology'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('gastroenterology', 'Gastroenterology'), ('general_surgery', 'General Surgery'), ('internal_medicine', 'Internal Medicine'), ('neurology', 'Neurology'), ('obstetrics_gynecology', 'Obstetrics and Gynecology'), ('ophthalmology', 'Ophthalmology'), ('orthopedic_surgery', 'Orthopedic Surgery'), ('otolaryngology', 'Otolaryngology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('urology', 'Urology')], max_length=60, verbose_name='Specialty'),
        ),
    ]
