# Generated by Django 3.2 on 2023-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0002_alter_medicalspecialty_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalspecialty',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
    ]
