# Generated by Django 3.2 on 2023-05-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0003_alter_medicalspecialty_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalspecialty',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
