# Generated by Django 4.2.1 on 2024-01-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0002_initial"),
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalinsurance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patient.patientextended",
            ),
        ),
    ]
