# Generated by Django 4.2.1 on 2024-01-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import person.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
        ("doctor", "0001_initial"),
        ("specialization", "0001_initial"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("person.person",),
        ),
        migrations.CreateModel(
            name="DoctorExtended",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/images"
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("appointment_price", models.PositiveIntegerField()),
                (
                    "clinic_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[person.validators.valid_phone_number],
                    ),
                ),
                ("qualifications", models.TextField()),
                (
                    "address",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.address",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="specialization.specialization",
                    ),
                ),
            ],
            options={
                "db_table": "doctor",
            },
            bases=("doctor.doctor",),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctorextended"
            ),
        ),
    ]
