# Generated by Django 3.2 on 2023-05-16 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinic', '0001_initial'),
        ('speciality', '0002_alter_medicalspecialty_specialty'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('qualifications', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='doctor_user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_users', to='speciality.medicalspecialty')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='doctor_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'default_related_name': 'doctor_users',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_day', models.CharField(max_length=10, null=True)),
                ('to_day', models.CharField(max_length=10, null=True)),
                ('from_hour', models.TimeField(null=True)),
                ('to_hour', models.TimeField(null=True)),
                ('examination_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.location')),
            ],
        ),
    ]
