# Generated by Django 3.2 on 2023-05-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('geo', '0001_initial'),
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('qualifications', models.TextField()),
                ('from_day', models.CharField(max_length=10)),
                ('to_day', models.CharField(max_length=10)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('examination_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.location')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speciality.medicalspecialty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
