# Generated by Django 4.2.1 on 2023-07-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_day", models.CharField(blank=True, max_length=10, null=True)),
                ("to_day", models.CharField(blank=True, max_length=10, null=True)),
                ("from_hour", models.TimeField(blank=True, null=True)),
                ("to_hour", models.TimeField(blank=True, null=True)),
                (
                    "examination_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "db_table": "doctor_profile",
            },
        ),
    ]
