# Generated by Django 4.2.1 on 2023-07-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geo", "0001_initial"),
        ("clinic", "0001_initial"),
        ("person", "0001_initial"),
        ("doctor", "0001_initial"),
        ("speciality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("person.person",),
        ),
        migrations.CreateModel(
            name="DoctorExtended",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/images"
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("qualifications", models.TextField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="geo.location"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="speciality.medicalspecialty",
                    ),
                ),
            ],
            options={
                "db_table": "doctor",
            },
            bases=("doctor.doctor",),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctorextended"
            ),
        ),
    ]
