# Generated by Django 3.2 on 2023-05-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('clinic', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='examination_price',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='from_day',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='to_day',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='to_hour',
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_day', models.CharField(max_length=10)),
                ('to_day', models.CharField(max_length=10)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('examination_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.location')),
            ],
        ),
    ]
