# Generated by Django 4.2.1 on 2023-08-13 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("person.person",),
        ),
        migrations.CreateModel(
            name="DoctorExtended",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/images"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("appointment_price", models.PositiveIntegerField()),
                ("qualifications", models.TextField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                        ]
                    ),
                ),
                ("location_details", models.TextField()),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                            ("", ""),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "doctor",
            },
            bases=("doctor.doctor",),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctorextended"
            ),
        ),
    ]
