# Generated by Django 4.2.1 on 2023-08-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorextended",
            name="clinic_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
