# Generated by Django 3.2 on 2023-05-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='examination_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='from_day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='from_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='to_day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='to_hour',
            field=models.TimeField(),
        ),
    ]
