# Generated by Django 4.2.1 on 2023-08-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_doctorextended_area_or_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorextended",
            name="area_or_center",
            field=models.CharField(
                choices=[
                    ("نجع حمادي", "نجع حمادي"),
                    ("دشنا", "دشنا"),
                    ("فرشوط", "فرشوط"),
                    ("قنا", "قنا"),
                    ("قفط", "قفط"),
                    ("قوص", "قوص"),
                    ("نقادة", "نقادة"),
                ]
            ),
        ),
    ]
