# Use an official Python runtime as the base image
FROM python:3.11.2

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Set the working directory in the container
# RUN mkdir -p /sakan/source

WORKDIR /source


# Copy the requirements file into the container
COPY requirements.txt requirements.txt 

# Install the Python dependencies
RUN pip3 install -r requirements.txt

# Copy the Django project code into the container
COPY . .

# Run the Django development server when the container starts

CMD ["gunicorn", "project.wsgi"]